version: '3.8'

services:
  db-eccar:
    image: mariadb:10.11
    container_name: eccar-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=eccarRootPass5555
      - MARIADB_DATABASE=eccardb
      - MARIADB_USER=eccaruser
      - MARIADB_PASSWORD=eccarpassword
    volumes:
      - db_data_eccar:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - eccar-network

  app-eccar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eccar-app
    restart: always
    ports:
      - "8002:8000"
    depends_on:
      - db-eccar
    environment:
      - PORT=8000
      - DB_HOST=db-eccar
      - DB_USER=eccaruser
      - DB_PASSWORD=eccarpassword
      - DB_DATABASE=eccardb
      - DB_PORT=3306
      - JWT_SECRET=eccarSuperSecretKey5555
      - NODE_ENV=production
    volumes:
      - uploads_data_eccar:/app/server/uploads
    networks:
      - eccar-network

volumes:
  db_data_eccar:
  uploads_data_eccar:

networks:
  eccar-network:
    driver: bridge
